name: Django Structure Recreation
description: Recreates the Django site structure with content types and pages
type: Site
install:
  # Core modules needed
  - node
  - field
  - text
  - path
  - pathauto
  - menu_ui
  - block
  - user
  - field_ui
  - views
  - views_ui

