name: 'Django Structure Recreation'
description: 'Recreates the Django site structure with content types and pages'
type: 'Site'

install:
  - node
  - field
  - text
  - path
  - menu_ui
  - views
  - views_ui

config:
  import:
    node: '*'
    path: '*'
  actions:
    system.site:
      simpleConfigUpdate:
        name: 'Django-Drupal POC'
        slogan: 'Hybrid Django-Drupal Architecture'

